export const categories = [
  { id: "engine", name: "Engine", icon: "engine" },
  { id: "brakes", name: "Brakes", icon: "disc" },
  { id: "suspension", name: "Suspension", icon: "spring" },
  { id: "electrical", name: "Electrical", icon: "zap" },
  { id: "accessories", name: "Accessories", icon: "briefcase" },
  { id: "tools", name: "Tools", icon: "wrench" },
]

export const products = [
  {
    id: "1",
    sku: "BR-8984X",
    brand: "BREMBO",
    name: "Rotor de Freno Perforado Alto Rendimiento",
    description: "Rotor de freno perforado y ranurado para máxima disipación de calor. Ideal para uso deportivo y condiciones extremas.",
    price: 145.99,
    originalPrice: 175.00,
    image: "/products/brake-rotor.jpg",
    category: "brakes",
    stock: "in_stock",
    badge: "CONFIRMADO",
    specs: {
      material: "Hierro fundido de alto carbono",
      diametro: "330mm",
      peso: "8.5kg",
    },
  },
  {
    id: "2",
    sku: "LZKR6B-10E",
    brand: "NGK",
    name: "Bujía de Iridio IX Larga Duración",
    description: "Bujía de iridio con electrodo central fino para máxima eficiencia de combustión y arranque confiable.",
    price: 12.50,
    originalPrice: null,
    image: "/products/spark-plug.jpg",
    category: "engine",
    stock: "in_stock",
    badge: "CONFIRMADO",
    specs: {
      tipo: "Iridio IX",
      gap: "0.8mm",
      rosca: "14mm",
    },
  },
  {
    id: "3",
    sku: "33-2438",
    brand: "K&N",
    name: "Filtro de Aire Deportivo Alto Flujo",
    description: "Filtro de aire lavable y reutilizable. Incrementa el flujo de aire hasta 50% más que los filtros convencionales.",
    price: 59.99,
    originalPrice: 75.00,
    image: "/products/air-filter.jpg",
    category: "engine",
    stock: "low_stock",
    badge: "POCO STOCK",
    specs: {
      material: "Algodón con aceite",
      tipo: "Panel",
      lavable: "Sí",
    },
  },
  {
    id: "4",
    sku: "3323",
    brand: "BOSCH",
    name: "Filtro de Aceite Premium Filtración Avanzada",
    description: "Filtro de aceite con tecnología de filtración multicapa para máxima protección del motor.",
    price: 14.25,
    originalPrice: null,
    image: "/products/oil-filter.jpg",
    category: "engine",
    stock: "in_stock",
    badge: null,
    specs: {
      tipo: "Cartucho",
      eficiencia: "99.9%",
      presion: "23 PSI",
    },
  },
  {
    id: "5",
    sku: "HD-8923",
    brand: "AUTOPRO",
    name: "Pastillas de Freno Cerámicas Heavy Duty (Eje Delantero)",
    description: "Potencia de frenado superior para condiciones extremas. Diseñadas para resistir altas temperaturas y reducir el desvanecimiento del freno bajo cargas pesadas.",
    price: 89.99,
    originalPrice: 110.00,
    image: "/products/brake-pads.jpg",
    category: "brakes",
    stock: "in_stock",
    badge: "ALTO RENDIMIENTO",
    specs: {
      material: "Cerámica de Fricción Avanzada",
      uso_sugerido: "Camiones ligeros, SUVs, Remolque",
      garantia: "Limitada de por vida (Desgaste normal excluido)",
      hardware: "Clips anti-ruido de acero inoxidable",
      part_number: "AP-HD8923-CER",
    },
  },
  {
    id: "6",
    sku: "RTR-5502",
    brand: "AUTOPRO",
    name: "Rotor de Freno Perforado y Ventilado",
    description: "Rotor de freno de alta calidad con perforaciones y ventilación para mejor disipación de calor.",
    price: 125.00,
    originalPrice: null,
    image: "/products/brake-rotor-2.jpg",
    category: "brakes",
    stock: "in_stock",
    badge: null,
    specs: {
      diametro: "320mm",
      tipo: "Ventilado perforado",
    },
  },
  {
    id: "7",
    sku: "FL-DOT4",
    brand: "AUTOPRO",
    name: "Líquido de Frenos Sintético DOT 4",
    description: "Líquido de frenos sintético de alta temperatura para sistemas ABS y convencionales.",
    price: 18.50,
    originalPrice: null,
    image: "/products/brake-fluid.jpg",
    category: "brakes",
    stock: "in_stock",
    badge: null,
    specs: {
      tipo: "DOT 4",
      contenido: "500ml",
    },
  },
  {
    id: "8",
    sku: "TL-BKP-01",
    brand: "AUTOPRO",
    name: "Kit Compresor de Pistón de Freno",
    description: "Herramienta profesional para comprimir pistones de freno durante el cambio de pastillas.",
    price: 35.00,
    originalPrice: null,
    image: "/products/brake-tool.jpg",
    category: "tools",
    stock: "in_stock",
    badge: null,
    specs: {
      material: "Acero cromado",
      tipo: "Universal",
    },
  },
  {
    id: "9",
    sku: "IN-89024X",
    brand: "K&N",
    name: "Kit de Admisión de Aire Frío V8",
    description: "Flujo de aire optimizado para motores de combustión interna de alto rendimiento. Malla de acero inoxidable.",
    price: 245.00,
    originalPrice: 289.00,
    image: "/products/cold-air-intake.jpg",
    category: "engine",
    stock: "in_stock",
    badge: null,
    specs: {
      compatibilidad: "V8 5.0L - 6.2L",
      material: "Aluminio pulido",
    },
  },
  {
    id: "10",
    sku: "BRK-C441-F",
    brand: "AUTOPRO",
    name: "Juego de Pastillas de Freno Cerámicas (Delanteras)",
    description: "Compuesto de baja emisión de polvo. Resistencia térmica extrema para frenadas de precisión.",
    price: 89.50,
    originalPrice: null,
    image: "/products/brake-pads-ceramic.jpg",
    category: "brakes",
    stock: "low_stock",
    badge: "POCO STOCK",
    specs: {
      posicion: "Delanteras",
      tipo: "Cerámicas",
    },
  },
]

export const vehicleYears = Array.from({ length: 30 }, (_, i) => (2024 - i).toString())

export const vehicleMakes = [
  "Chevrolet",
  "Ford",
  "Toyota",
  "Honda",
  "Nissan",
  "Volkswagen",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Mazda",
  "Hyundai",
  "Kia",
  "Jeep",
  "RAM",
  "GMC",
]

export const vehicleModels: Record<string, string[]> = {
  Chevrolet: ["Silverado", "Camaro", "Tahoe", "Suburban", "Colorado", "Equinox", "Malibu"],
  Ford: ["F-150", "Mustang", "Explorer", "Ranger", "Bronco", "Edge", "Escape"],
  Toyota: ["Camry", "Corolla", "Tacoma", "Tundra", "RAV4", "Highlander", "4Runner"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "HR-V", "Ridgeline", "Odyssey"],
  Nissan: ["Altima", "Sentra", "Frontier", "Titan", "Rogue", "Pathfinder", "Maxima"],
  Volkswagen: ["Jetta", "Golf", "Tiguan", "Atlas", "Passat", "Arteon", "Taos"],
  BMW: ["Serie 3", "Serie 5", "X3", "X5", "Serie 7", "X1", "Z4"],
  "Mercedes-Benz": ["Clase C", "Clase E", "GLC", "GLE", "Clase S", "CLA", "GLA"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "TT"],
  Mazda: ["3", "6", "CX-5", "CX-9", "MX-5 Miata", "CX-30", "CX-50"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Kona", "Accent"],
  Kia: ["Forte", "K5", "Sportage", "Sorento", "Telluride", "Soul", "Seltos"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Gladiator", "Renegade"],
  RAM: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
  GMC: ["Sierra", "Canyon", "Yukon", "Terrain", "Acadia", "Savana"],
}

export const engineTypes = [
  "2.0L 4-Cyl",
  "2.5L 4-Cyl",
  "3.5L V6",
  "3.6L V6",
  "5.0L V8",
  "5.3L V8",
  "5.7L V8",
  "6.2L V8",
  "2.0L Turbo",
  "3.0L Turbo",
  "Eléctrico",
  "Híbrido",
]
